---
title: "Create plots"
author: "Kate Tran"
date: "2022-12-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(lubridate)
library(usmap)
library(usmapdata)
library(scales)
```

```{r}
climate_data <- readRDS("../data/dataset_14d_4to10_21sites.rds") %>% 
  mutate(eventname = recode(eventname,
                            baseline_year_1_arm_1 = "bl" ,
                            `1_year_follow_up_y_arm_1` = "1y",
                            `2_year_follow_up_y_arm_1` = "2y"),
         eventname = factor(eventname, c("bl", "1y", "2y")))
```

```{r}
# Figure S1
# Number of participants across months
ggplot(climate_data) + aes(x = month_14d) +
  geom_bar(fill = "royalblue4") +
  labs(x = "",
       y = "Number of participants") +
  scale_y_continuous(breaks=seq(0, 2000, 500)) +
  scale_x_continuous(breaks = seq(4,10,1), labels = c("Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct")) +
  theme_bw() +
  theme(axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14)
  )

# ggsave("../plots/participants_across_time_noyear_020223.tiff", dpi = 400, width = 6, height = 4)
```

```{r}
# Figure 1
# The association between extreme heat and KSADS externalizing scores by stations
# 21 sites
climate_plot <- climate_data %>% 
  mutate(station = recode(station,
                          USW00093134 = "California (Los Angeles) 1",
                          USC00085667 = "Florida (Miami)",
                          USC00421446 = "Utah",
                          USW00053908 = "Oklahoma",
                          USW00013782 = "South Carolina",
                          USC00356749 = "Oregon",
                          USC00046646 = "California (Menlo Park)",
                          USW00093107 = "California (La Jolla)",
                          USC00049152 = "California (Los Angeles) 2",
                          USW00000160 = "Colorado",
                          USW00012816 = "Florida (Gainesville)",
                          USW00093784 = "Maryland",
                          USC00200230 = "Michigan",
                          USC00214884 = "Minnesota",
                          USC00360861 = "Pennsylvania",
                          USW00014768 = "New York",
                          USW00014742 = "Vermont",
                          USC00475474 = "Wisconsin",
                          USW00013740 = "Virginia",
                          USC00237452 = "Missouri",
                          USW00014758 = "Connecticut"
                          ))
# USW00093134	4641 Sunset Blvd. Los Angeles, CA 90027
# USC00085667	11200 SW 8th Street Miami, FL 33199
# USC00421446	501 Chipeta Way Salt Lake City, UT 84108
# USW00053908	6655 S Yale Ave, Tulsa, OK 74136
# USW00013782	30 Bee Street Charleston, SC 29425
# USC00356749	3181 SW Sam Jackson Park Rd, Portland, OR 97239
# USC00046646	333 Ravenswood Ave. Menlo Park, CA 94025
# USW00093107	9500 Gilman Drive La Jolla, CA 92093
# USC00049152	760 Westwood Plaza Los Angeles, CA 90095
# USW00000160	1777 Exposition Drive Boulder, CO 80301
# USW00012816	1600 SW Archer Rd, Gainesville, FL 32610
# USW00093784	670 W Baltimore St, Baltimore, MD 21201
# USC00200230	4250 Plymouth Rd. Ann Arbor, MI 48109
# USC00214884	75 East River Parkway Minneapolis, MN 55455
# USC00360861	3811 O'Hara Street, Pittsburgh, PA 15213
# USW00014768	430 Elmwood Ave Rochester, NY 14620
# USW00014742	111 Colchester Ave. Burlington, VT 05401
# USC00475474	10437 W Innovation Dr Wauwatosa, WI 53226
# USW00013740	203 E Cary Street, Richmond, VA 23219
# USC00237452	4560 Clayton Avenue, St. Louis, MO 63110
# USW00014758	2 Hillhouse Ave New Haven, CT 06511

plot1 <- climate_plot %>% ggplot(aes(x = scale(dx90), y = scale(ksads_externalizing_exclude_attentation_symptoms_sum))) +
  geom_point(color = "darkslategray4") +
  geom_smooth(method = "lm", se = TRUE, fill = "blue", color = "red") +
  facet_wrap(~station, ncol = 5) +
  labs(x = "",
       y = "Standardized lifetime (past/ current) KSADS externalizing scores",
       # y = "",
       # title = "Association between number of extreme heat days per month and\nlifetime externalizing scores\n",
       subtitle = "Individual ABCD study sites") +
  theme_bw() +
  theme(axis.text.x = element_text(size = 23, face = "bold"),
        axis.text.y = element_text(size = 23, face = "bold"),
        axis.title.y = element_text(size = 22, face = "bold"),
        plot.title = element_text(size = 23.5, hjust = 0.5, colour = "black", face = "bold"),
        plot.subtitle = element_text(size = 23.5, hjust = 0.5, face = "bold"),
        strip.text = element_text(size = 18, face = "bold"),
        axis.ticks = element_line(size = 0.5))
# ggsave(filename = "../plots/association_by_stations_21sites_020223.png", width = 18, height = 11, dpi = 620)


plot2 <- climate_plot %>% ggplot(aes(x = scale(dx90), y = scale(ksads_externalizing_exclude_attentation_symptoms_sum))) +
  geom_point(color = "darkslategray4") +
  geom_smooth(method = "lm", se = TRUE, fill = "blue", color = "red") +
  labs(x = expression("Standardized number of extreme heat days (" >=90 ~ "°F) per month"),
       y = " ",
       subtitle = "Among all ABCD study sites") +
  theme_bw() +
  theme(axis.text.x = element_text(size = 23, face = "bold"),
        axis.text.y = element_text(size = 23, face = "bold"),
        axis.title.x = element_text(size = 25, face = "bold"),
        axis.title.y = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(size = 23.5, hjust = 0.5, face = "bold"),
        axis.ticks = element_line(size = 0.5))
# ggsave(filename = "../plots/association_all_stations_21sites_020223.png", width = 8, height = 6, dpi = 620)

ggpubr::ggarrange(plot1, plot2, ncol = 1, heights = c(11, 7), widths = c(12, 7))
ggsave(filename = "../plots/merged_020223.tiff", width = 18, height = 17, dpi = 320)
```


```{r}
# Figure 2
# Map of stations
statelists <- data.frame(
  stringsAsFactors = FALSE,
             state = c("California", "Colorado", "Connecticut", "Florida", "Maryland", "Michigan", "Minnesota", "Missouri", "New York",
                       "Oklahoma", "Oregon", "Pennsylvania", "South Carolina", "Utah", "Vermont", "Virginia", "Wisconsin"),
         stateabbr = c("CA", "CO", "CT", "FL", "MD", "MI", "MN", "MO", "NY", "OK", "OR", "PA", "SC", "UT", "VT", "VA", "WI"),
                 N = rep(1L, 17),
              fips = c("06", "08", "09", "12", "24", "26", "27", "29", "36", "40", "41", "42", "45", "49", "50", "51", "55")
  )

# Get centroids
centroid_labels <- centroid_labels("states") #usmapdata

statelists <- statelists %>% 
  bind_rows(centroid_labels %>% select(state = full, stateabbr = abbr, fips) %>% 
  mutate(N = 0) %>% 
  filter(
    !state %in% statelists$state
  ))

site_data <- data.frame(lon = c(-118.29055,  -80.3762, -111.82303,  -95.92204,  -79.94864, -122.68669, -122.17469, -117.23927, 
                                -118.44428, -105.24709,  -82.36370,  -76.62623,  -83.67669,  -93.23764,  -79.95985,
                                -77.62694,  -73.19292,  -88.04461,  -77.44298,  -90.26396,  -72.92465),
                        lat = c(34.09820, 25.75539, 40.75910, 36.06645, 32.78691, 45.49985, 37.45661, 32.87581, 34.06577, 40.01644, 
                                29.63123, 39.28974, 42.30939, 44.97689, 40.44355, 43.12416, 44.47849, 43.04401,
                                37.54053, 38.63299, 41.31190))

transformed_data <- usmap_transform(site_data)

# Get mean-SD of extreme heat at each site
climate_data %>% 
  group_by(station) %>% 
  dplyr::summarise(Mean = round(mean(dx90, na.rm=TRUE), 1),
            SD = round(sd(dx90, na.rm=TRUE), 1))
```

``` {r}
# create plot 
plot_usmap(data = statelists, regions = "state", values = "N") +
  scale_fill_continuous(low = "azure", high = "azure", limits = c(0,2)) + #high = "lightblue3", 
  labs(fill = "Count") +
  theme(panel.background = element_rect(color = "black", fill = "white"),
        legend.position = "none",
        plot.title = element_text(hjust = 0.5, face = "bold", size = 15)) +
  geom_point(data = transformed_data, 
             aes(x = x, y = y), 
             color = "red",
             size = 3,
             shape = 17) +
  annotate(geom = "text", x = 2222731, y = -1909255.3, label = 'bold("(16.2±9.9)")', color = "blue", size = 3, parse = TRUE) + #USC00085667
  annotate(geom = "text", x = 2442731, y = -1909255.3, label = 'bold("*")', color = "blue", size = 5, parse = TRUE) + #USC00085667 #
  
  annotate(geom = "text", x = 261461.6, y = -1080424.8, label = 'bold("(12.9±9.7)")', color = "blue", size = 3, parse = TRUE) + #USW00053908
  annotate(geom = "text", x = 481461.6, y = -1080424.8,label = 'bold("*")', color = "blue", size = 5, parse = TRUE) + #USW00053908
  
  annotate(geom = "text", x = -1688710, y = 186836.9, label = 'bold("(1.7±2.6)")', color = "blue", size = 3, parse = TRUE) + #USC00356749
  annotate(geom = "text", x = -1488710, y = 186836.9, label = 'bold("*")', color = "blue", size = 5, parse = TRUE) + #USC00356749
  
  annotate(geom = "text", x = -1770656, y = -721391.9, label = 'bold("(2.1±2.4)")', color = "blue", size = 3, parse = TRUE) + #USC00046646
  annotate(geom = "text", x = -1575656, y = -721391.9, label = 'bold("*")', color = "blue", size = 5, parse = TRUE) + #USC00046646
  
  annotate(geom = "text", x = -1950056, y = -1073855, label = 'bold("(1.5±2.0)")', color = "blue", size = 3, parse = TRUE) + #USC00049152
  annotate(geom = "text", x = -1765056, y = -1073855, label = 'bold("*")', color = "blue", size = 5, parse = TRUE) + #USC00049152
  
  annotate(geom = "text", x = 2312549, y = -352730.3, label = 'bold("(8.7±7.2)")', color = "blue", size = 3, parse = TRUE) + #USW00093784
  annotate(geom = "text", x = 2512549, y = -352730.3, label = 'bold("*")', color = "blue", size = 5, parse = TRUE) + #USW00093784
  
  annotate(geom = "text", x = -992155.1, y = -500883.8, label = 'bold("(6.2±8.4)")', color = "blue", size = 3, parse = TRUE) + #USC00421446
  annotate(geom = "text", x = -802155.1, y = -500883.8, label = 'bold("*")', color = "blue", size = 5, parse = TRUE) + #USC00421446
  
  annotate(geom = "text", x = 800130.3, y = -278193, label = 'bold("(2.0±1.8)")', color = "blue", size = 3, parse = TRUE) + #USC00475474
  annotate(geom = "text", x = 990130, y = -278193, label = 'bold("*")', color = "blue", size = 5, parse = TRUE) + #USC00475474
  
  annotate(geom = "text", x = 674046.2, y = -780478.2, label = 'bold("(10.8±6.7)")', color = "blue", size = 3, parse = TRUE) + #USC00237452
  annotate(geom = "text", x = 894046.2, y = -780478.2, label = 'bold("*")', color = "blue", size = 5, parse = TRUE) + #USC00237452
  
  annotate(geom = "text", x = 1336727, y = -303404.1, label = 'bold("(2.4±3.1)")', color = "blue", size = 3, parse = TRUE) + #USC00200230
  annotate(geom = "text", x = 1526727, y = -303404.1, label = 'bold("*")', color = "blue", size = 5, parse = TRUE) + #USC00200230
  
  annotate(geom = "text", x = 420130.3, y = -90807, label = 'bold("(1.4±2.0)")', color = "blue", size = 3, parse = TRUE) + #USC00214884
  annotate(geom = "text", x = 620130.3, y = -90807, label = 'bold("*")', color = "blue", size = 5, parse = TRUE) + #USC00214884
  
  annotate(geom = "text", x = 1736727, y = -203404.1, label = 'bold("(2.1±2.9)")', color = "blue", size = 3, parse = TRUE) + #USC00360861
  annotate(geom = "text", x = 1926727, y = -203404.1, label = 'bold("*")', color = "blue", size = 5, parse = TRUE) + #USC00360861
  
  annotate(geom = "text", x = -492155.1, y = -633883.8, label = 'bold("(6.7±6.3)")', color = "blue", size = 3, parse = TRUE) + #USW00000160
  annotate(geom = "text", x = -302155.1, y = -633883.8, label = 'bold("*")', color = "blue", size = 5, parse = TRUE) + #USW00000160

  annotate(geom = "text", x = 2052731, y = -1529255.3, label = 'bold("(17.3±8.9)")', color = "blue", size = 3, parse = TRUE) + #USW00012816
  annotate(geom = "text", x = 2272731, y = -1529255.3, label = 'bold("*")', color = "blue", size = 5, parse = TRUE) + #USW00012816

  annotate(geom = "text", x = 2302549, y = -572730.3, label = 'bold("(9.3±7.6)")', color = "blue", size = 3, parse = TRUE) + #USW00013740
  annotate(geom = "text", x = 2502549, y = -572730.3, label = 'bold("*")', color = "blue", size = 5, parse = TRUE) + #USW00013740

  annotate(geom = "text", x = 2082731, y = -1129255.3, label = 'bold("(3.5±3.1)")', color = "blue", size = 3, parse = TRUE) + #USW00013782
  annotate(geom = "text", x = 2282731, y = -1129255.3, label = 'bold("*")', color = "blue", size = 5, parse = TRUE) + #USW00013782

  annotate(geom = "text", x = 1836727, y = 366595.9, label = 'bold("(1.8±2.8)")', color = "blue", size = 3, parse = TRUE) + #USW00014742
  annotate(geom = "text", x = 2026727, y = 366595.9, label = 'bold("*")', color = "blue", size = 5, parse = TRUE) + #USW00014742

  annotate(geom = "text", x = 2482549, y = -50730.3, label = 'bold("(1.4±2.1)")', color = "blue", size = 3, parse = TRUE) + #USW00014758
  annotate(geom = "text", x = 2682549, y = -50730.3, label = 'bold("*")', color = "blue", size = 5, parse = TRUE) + #USW00014758

  annotate(geom = "text", x = 1596727, y = 120404.1, label = 'bold("(2.0±2.9)")', color = "blue", size = 3, parse = TRUE) + #USW00014768
  annotate(geom = "text", x = 1786727, y = 120404.1, label = 'bold("*")', color = "blue", size = 5, parse = TRUE) + #USW00014768

  annotate(geom = "text", x = -1380056, y = -1183855, label = 'bold("(3.8±1.4)")', color = "blue", size = 3, parse = TRUE) + #USW00093107
  annotate(geom = "text", x = -1195056, y = -1183855, label = 'bold("*")', color = "blue", size = 5, parse = TRUE) + #USW00093107

  annotate(geom = "text", x = -1470056, y = -1023855, label = 'bold("(4.2±3.5)")', color = "blue", size = 3, parse = TRUE) + #USW00093134
  annotate(geom = "text", x = -1275056, y = -1023855, label = 'bold("*")', color = "blue", size = 5, parse = TRUE) + #USW00093134
  
  # Add the footnotes
  annotate(geom = "text", x = -991462, y = -2774255, label= 'bold("*")', color = "blue", size = 5.5, parse = TRUE) +
  annotate(geom = "text", x = 909462, y = -2759255, label = "'Mean ± Standard Deviation of extreme heat days ('>=90~'°F) per month'", color = "blue", size = 4.2, parse = TRUE, fontface = "bold") +
  geom_point(data = data.frame(x = -991462, y = -2519255), aes(x = x, y = y),  color = "red", size = 3.5, shape = 17) +
  annotate(geom = "text", x = 623538, y = -2509255, label= "ABCD sites with corresponding temperature data available", color = "blue", size = 4.2)

ggsave("../plots/map_020223.tiff", dpi = 320, width = 8, height = 6)
```






















